services:
  airflow-webserver:
    image: custom-airflow-spark:latest
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: bash -c "airflow db init && airflow db upgrade && airflow webserver"
    networks:
      - airflow_network
    depends_on:
      - airflow-db

  airflow-scheduler:
    image: custom-airflow-spark:latest
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: bash -c "airflow db init && airflow db upgrade && airflow scheduler"
    networks:
      - airflow_network
    depends_on:
      - airflow-db

  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  spark:
    image: spark-custom:latest
    container_name: spark-container
    volumes:
      - ../shared_volume:/shared_volume
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge
