# Refer to table and field names indirectly
# Each DIF MD table should be defined here and only these constants used in the code

class TableNames:
    Project = "Project"
    AssetGroup = "Asset_Group"
    Asset = "Asset"
    Field = "Field"
    IncrementalIdentifier = "Incremental_Load"
    AssetHistory = "Asset_History"
    AssetStatus = "Asset_Status"
    HistoricalLoad = "Historical_Load"
    Holiday_Calendar = "Holiday_Calendar"

class ProjectColumns:
    Project_Key = "Project_Key"
    ProjectName = "Project_Name"
    Node = "Node_Name"
    Project_Description = "Project_Description"
    Project_Status_Code = "Project_Status_Code"
    Business_Area_Code = "Business_Area_Code"
    Project_Code = "Project_Code"
    Data_Owner_Name = "Data_Owner_Name"

class AssetGroupColumns:
    Project_Key = "Project_Key"
    Asset_Group_Key = "Asset_Group_Key"
    Asset_Group_Name = "Asset_Group_Name"
    Frequency_Code = "Frequency_Code"
    Asset_Group_Description = "Asset_Group_Description"
    Asset_Group_Custom_Exits_String = "Asset_Group_Custom_Exits_String"

class AssetColumns:
    Asset_Key = "Asset_Key"
    Asset_Group_Key = "Asset_Group_Key"
    Asset_Name = "Asset_Name"
    Asset_Status_Code = "Asset_Status_Code"
    Sequence_Number = "Sequence_Number"
    Asset_Description = "Asset_Description"
    Source_To_Ingest_Indicator = "Source_To_Ingest_Indicator"
    Source_To_Ingest_Type_Code = "Source_To_Ingest_Type_Code"
    Source_To_Ingest_Reference_String = "Source_To_Ingest_Reference_String"
    Source_To_Ingest_Details_String = "Source_To_Ingest_Details_String"
    Multiple_Files_Indicator = "Multiple_Files_Indicator"
    Ingest_File_Pattern_String = "Ingest_File_Pattern_String"
    Multiple_Files_Horizon_Number = "Multiple_Files_Horizon_Number"
    Multiple_Files_Sequence_Code = "Multiple_Files_Sequence_Code"
    Multiple_Files_Sequence_Check_Indicator = "Multiple_Files_Sequence_Check_Indicator"
    Multiple_Files_Failure_Action_Code = "Multiple_Files_Failure_Action_Code"
    Early_Late_File_Rule_String = "Early_Late_File_Rule_String"
    Decrypt_Indicator = "Decrypt_Indicator"
    Decrypt_Info_String = "Decrypt_Info_String"
    Unzip_Indicator = "Unzip_Indicator"
    Unzip_Info_String = "Unzip_Info_String"
    Embedded_File_Name = "Embedded_File_Name"
    File_Type_Code = "File_Type_Code"
    Extract_Info_String = "Extract_Info_String"
    Validation_Rules_String = "Validation_Rules_String"
    Min_File_Size_KB_Number = "Min_File_Size_KB_Number"
    Min_Raw_Records_Number = "Min_Raw_Records_Number"
    Min_Failure_Action_Code = "Min_Failure_Action_Code"
    Container_Name = "Container_Name"
    Folder_Path_Name = "Folder_Path_Name"
    Folder_Date_Format_String = "Folder_Date_Format_String"
    Raw_Table_Name = "Raw_Table_Name"
    Processed_Table_Name = "Processed_Table_Name"
    Load_Type_Code = "Load_Type_Code"
    Custom_Exits_String = "Custom_Exits_String"
    Other_String = "Other_String"
    Asset_Record_Created_Date = "Asset_Record_Created_Date"
    Asset_Record_Modified_Date = "Asset_Record_Modified_Date"
    Incremental_Load_String = "Incremental_Load_String"
    Incremental_Load_Type_Code = "Incremental_Load_Type_Code"


class FieldColumns:
    Field_Key = "Field_Key"
    Asset_Key = "Asset_Key"
    Source_Field_Name = "Source_Field_Name"
    Field_Sequence_Number = "Field_Sequence_Number"
    Target_Field_Name = "Target_Field_Name"
    Field_Description = "Field_Description"
    Example_String = "Example_String"
    IsKey_Indicator = "IsKey_Indicator"
    Partitioned_Indicator = "Partitioned_Indicator"
    Incremental_Indicator = "Incremental_Indicator"
    Snapshot_Indicator = "Snapshot_Indicator"
    PII_Indicator = "PII_Indicator"
    Data_Classification_Code = "Data_Classification_Code"
    Data_Protection_Code = "Data_Protection_Code"
    Conditional_Protection_Rule_String = "Conditional_Protection_Rule_String"
    Exclude_From_Processed_Indicator = "Exclude_From_Processed_Indicator"
    Anonymization_Code = "Anonymization_Code"
    Derivation_Rule_String = "Derivation_Rule_String"
    Source_Data_Type_Code = "Source_Data_Type_Code"
    Field_Extract_Info_String = "Field_Extract_Info_String"
    Conversion_Rule_String = "Conversion_Rule_String"
    Target_Data_Type_Code = "Target_Data_Type_Code"
    Action_Flags_String = "Action_Flags_String"
    Validation_Rules_String = "Validation_Rules_String"
    Field_Record_Created_Date = "Field_Record_Created_Date"
    Field_Record_Modified_Date = "Field_Record_Modified_Date"


class IncrementalLoadColumns:
    Incremental_Load_Key = "Incremental_Load_Key"
    Asset_Key = "Asset_Key"
    Incremental_Source_Field_Name = "Incremental_Source_Field_Name"
    Data_Type_Code = "Data_Type_Code"
    Last_Value_String = "Last_Value_String"
    Last_Updated_Date = "Last_Updated_Date"
    Incremental_Load_Record_Created_Date = "Incremental_Load_Record_Created_Date"
    Incremental_Load_Record_Modified_Date = "Incremental_Load_Record_Modified_Date"


class AssetHistoryColumns:
    Asset_History_Key = "Asset_History_Key"
    Asset_Key = "Asset_Key"
    Asset_History_Name = "Asset_History_Name"
    Business_Date = "Business_Date"
    Run_Identifier = "Run_Identifier"
    File_Name = "File_Name"
    Step_Name = "Step_Name"
    Status_Code = "Status_Code"
    Status_Details_String = "Status_Details_String"
    Step_Details_String = "Step_Details_String"
    Asset_History_Record_Created_Date = "Asset_History_Record_Created_Date"
    Asset_History_Record_Modified_Date = "Asset_History_Record_Modified_Date"

class AssetStatusColumns:
    Asset_Status_Key = "Asset_Status_Key"
    Asset_Key = "Asset_Key"
    Asset_Status_Name = "Asset_Status_Name"
    Asset_Status_Code = "Asset_Status_Code"
    Asset_Status_Record_Created_Date = "Asset_Status_Record_Created_Date"
    Asset_Status_Record_Modified_Date = "Asset_Status_Record_Modified_Date"

class HistoricalLoadColumns:
    Historical_Load_Key = "Historical_Load_Key"
    Asset_Key = "Asset_Key"
    Historical_Sequence_Number = "Historical_Sequence_Number"
    Historical_Sql_String = "Historical_Sql_String"
    Historical_Load_Record_Created_Date = "Historical_Load_Record_Created_Date"
    Historical_Load_Record_Modified_Date = "Historical_Load_Record_Modified_Date"

class HolidayCalendarColumns:
    Holiday_Calendar_Key = "Holiday_Calendar_Key"
    Holiday_Name = "Holiday_Name"
    Calendar_Name = "Calendar_Name"
    Holiday_Date = "Holiday_Date"
    Holiday_Calendar_Record_Created_Date = "Holiday_Calendar_Record_Created_Date"
    Holiday_Calendar_Record_Modified_Date = "Holiday_Calendar_Record_Modified_Date"


